Updates

diff --git a/services.d/connect/run b/services.d/connect/run
--- a/services.d/connect/run
+++ b/services.d/connect/run
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/with-contenv sh
 
 function waitPort() {
   for i in 1 .. 30 ; do
@@ -11,19 +11,16 @@ function waitPort() {
   return 1
 }
 
-while true ; do
-  if waitPort $ADB_SERVER_PORT ; then
-      for device in $ADB_DEVICES ; do
-        msg=`adb connect $device 2>&1`
-        if [ $? -ne 0 ] ; then
-          echo "ADB failed to connect to $device"
-          echo $msg
-        fi
-      done
-      sleep 60
-  else
-    echo "Timed out waiting for ADB server on port $ADB_SERVER_PORT"
-    exit 1
-  fi
-done
-exit 0
+if waitPort $ADB_SERVER_PORT ; then
+    for device in $ADB_DEVICES ; do
+      msg=`adb connect $device 2>&1`
+      if [ $? -ne 0 ] ; then
+        echo "ADB failed to connect to $device"
+        echo $msg
+      fi
+    done
+else
+  echo "Timed out waiting for ADB server on port $ADB_SERVER_PORT"
+  exit 1
+fi
+sleep 60
